version: '3.8'

services:
  app:
    build:
      context: .
    container_name: holiday_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - holiday-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=holiday_app
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: holiday_db
    ports:
      - "3306:3306"
    networks:
      - holiday-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=holiday_app
    volumes:
      - db-data:/var/lib/mysql
